# -*- coding: utf-8 -*-
"""Project (422)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFem7mTigmqnopJSzJbykhGcjkcivFud

# **Title: IoT Network Traffic Analysis**
# Dataset:
https://www.kaggle.com/datasets/emilynack/aci-iot-network-traffic-dataset-2023



**Reference:** Nathaniel Bastian, David Bierbrauer, Morgan McKenzie, Emily Nack, December 29, 2023, " ACI IoT Network Traffic Dataset 2023", IEEE Dataport, doi: https://dx.doi.org/10.21227/qacj-3x32.

Report: [Link](https://docs.google.com/document/d/15o_UhTC8v17gbnlxSAIEWiN4ZomAUSgxckqmAYrV1PU/edit?usp=sharing)
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')
dataset = pd.read_csv('/content/drive/My Drive/Dataset2/dataset.csv')

"""##**Data Analysis**##"""

main_frame = pd.DataFrame(dataset)
main_frame.shape

null=main_frame.isnull().sum().sum()
print(f"Total number of Null values in Dataset: {null}")

ac=main_frame['Label'].unique()
for i in ac:
  print(i)

non_numeric_columns = main_frame.select_dtypes(exclude='number').columns
num_non_numeric_columns = len(non_numeric_columns)

print(f'The number of columns with non-numeric values is: {num_non_numeric_columns}')
print('Non-numeric columns:', non_numeric_columns)

main_frame.head(100)

from sklearn.model_selection import train_test_split
Y = main_frame['Label']

dataset_subset, _ = train_test_split(main_frame, test_size=(len(main_frame) - 30000), stratify=Y, random_state=42)

label_distribution = dataset_subset['Label'].value_counts()
print("Label distribution in the subset:")
print(label_distribution)

print("Shape of the subset:", dataset_subset.shape)
main_frame=dataset_subset

null=main_frame.isnull().sum().sum()

print(f"Total number of Null values in Dataset: {null}")

"""##**Pre-Processing**##

Some Data Preprocessing Techniques:



*  Deleting null values
*  Imputation for missing values
*  Handling Categorical Features
*  Feature Normalization/Scaling
*  Feature Engineering
*  Feature Selection

###Null Value###

Removing Rows with null value:
"""

print("Number of rows with null values in Flow Bytes column: ", main_frame['Flow Bytes/s'].isnull().sum())

dataset = main_frame[main_frame['Flow Bytes/s'].notnull()]

print("Shape after removing null values: ", dataset.shape)

null=dataset.isnull().sum().sum()

print(f"Total number of Null values in Dataset: {null}")

"""###Categorical Values###

####Encodiong Categorical values (Connection Type) to int:####
"""

print("Unique values in 'Connection Type':", dataset['Connection Type'].unique())

if not dataset['Connection Type'].isin([0, 1]).all():
  dataset['Connection Type'] = dataset['Connection Type'].str.strip().str.lower()
  dataset['Connection Type'] = dataset['Connection Type'].map({'wired': 0, 'wireless': 1})

print(dataset['Connection Type'].unique())

"""####Removing Categorical Features:####"""

columns_to_drop = ['Flow ID', 'Src IP', 'Dst IP', 'Timestamp','Src Port', 'Dst Port']
dataset = dataset.drop(columns=columns_to_drop, axis=1)

"""###Feature Engineering###

####Scaling down 10^15 values:####
"""

import pandas as pd

threshold = 10**12

numeric_columns = dataset.select_dtypes(include=['float64', 'int64'])
large_value_columns = [col for col in numeric_columns.columns if numeric_columns[col].max() > threshold]
dataset[large_value_columns] = dataset[large_value_columns] / 10**16
print(dataset[large_value_columns].head())

"""####Replaceing Inf values with NaN and removing them:####




"""

import numpy as np

inf_counts = {
    'Flow Bytes/s': np.isinf(dataset['Flow Bytes/s']).sum(),
    'Flow Packets/s': np.isinf(dataset['Flow Packets/s']).sum()
}

print("Number of 'inf' values:")
for column, count in inf_counts.items():
    print(f"{column}: {count}")

dataset.replace([np.inf, -np.inf], np.nan, inplace=True)
main_frame=dataset

main_frame = dataset.dropna(subset=['Flow Bytes/s', 'Flow Packets/s'])
print("Shape after removing rows with 'inf' values:", main_frame.shape)
print("Number of rows with null values in Flow Bytes column: ", main_frame['Flow Bytes/s'].isnull().sum())

dataset = main_frame[main_frame['Flow Bytes/s'].notnull()]
print("Shape after removing null values: ", dataset.shape)

"""###Feature Scaling###"""

from sklearn.preprocessing import StandardScaler
import pandas as pd
numeric_columns = dataset.select_dtypes(include=['float64', 'int64']).columns

scaler = StandardScaler()
scaled_features = scaler.fit_transform(dataset[numeric_columns])

scaled_dataset = dataset.copy()
scaled_dataset[numeric_columns] = scaled_features

print(scaled_dataset.head())

"""Removing scaled Null values:"""

null=dataset.isnull().sum().sum()
print(null)

dataset = dataset.dropna()
print("Shape after removing rows with null values:", dataset.shape)

"""###Feature Selection###"""

dataset = dataset.loc[:, ~dataset.columns.str.contains('mean', case=False)]
print("Shape after dropping columns with 'mean':", dataset.shape)

print("Remaining columns:", dataset.columns.tolist())
null=dataset.isnull().sum().sum()
print(null)

"""##**Seperating Trainning Data and Test Data**##"""

from sklearn.model_selection import train_test_split
Y=dataset['Label']
train_set, test_set = train_test_split(dataset, test_size=0.3, random_state=42,stratify=Y)


X_train = train_set.drop('Label', axis=1)
Y_train = train_set['Label']


X_test = test_set.drop('Label', axis=1)
Y_test = test_set['Label']

"""##**Data Visualization**##

Correlation Heatmap of the entire Dataset:
"""

target_feature = 'Label'


selected_columns = dataset.columns[dataset.columns != target_feature]


sampled_data = dataset.groupby(target_feature, group_keys=False).apply(lambda x: x.sample(min(len(x), 50)))


correlation_matrix = sampled_data[selected_columns].corr(numeric_only=True)

plt.figure(figsize=(15, 12))


sns.heatmap(correlation_matrix, cmap='coolwarm', vmin=-1, vmax=1, annot=False)


plt.show()

"""##**Correlation heatmap of 20 random features to understand the relations:**##"""

import random

target_feature = 'Label'

selected_columns = dataset.columns[dataset.columns != target_feature]


random_columns = random.sample(selected_columns.tolist(), 20)

sampled_data = dataset.groupby(target_feature, group_keys=False).apply(lambda x: x.sample(min(len(x), 50)))


correlation_matrix = sampled_data[random_columns].corr(numeric_only=True)

plt.figure(figsize=(15, 12))

sns.heatmap(correlation_matrix, cmap='coolwarm', vmin=-1, vmax=1, annot=False)

plt.show()

"""Data Distribution of Trainning Set:"""

plt.figure(figsize=(35, 6))
plt.subplot(1, 2, 1)
sns.countplot(x='Label', data=train_set)
plt.title('Training Set - Label Distribution')
plt.show()

"""Data Distribution of Test Set:"""

plt.figure(figsize=(35, 6))
plt.subplot(1, 2, 2)
sns.countplot(x='Label', data=test_set)
plt.title('Testing Set - Label Distribution')
plt.show()

"""## **Trainning and Prediction Accuracy:**##

###**Model 1: Decision Tree (RandomForestClassifier)**###
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model = RandomForestClassifier(n_estimators=20, random_state=42)
model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy:.2f}')

print(classification_report(Y_test, Y_pred))

"""Visualization:"""

from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(Y_test, Y_pred)

plt.figure(figsize=(20, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix For RandomForrestClassifier')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

class_accuracy = conf_matrix.diagonal() / conf_matrix.sum(axis=1)

plt.figure(figsize=(18, 6))
sns.barplot(x=model.classes_, y=class_accuracy, color='skyblue')
plt.title('Prediction Accuracy for Each Class')
plt.xlabel('Activity')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.show()

"""###**Model 2: K-Nearest Neighbors (KNeighborsClassifier)**###"""

from sklearn.neighbors import KNeighborsClassifier


knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, Y_train)

Y_pred_knn = knn_model.predict(X_test)
accuracy_knn = accuracy_score(Y_test, Y_pred_knn)
print(f'K-Nearest Neighbors Accuracy: {accuracy_knn:.2f}')

print('Classification Report for K-Nearest Neighbors:')
print(classification_report(Y_test, Y_pred_knn))

"""Visualization"""

from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(Y_test, Y_pred_knn)


plt.figure(figsize=(20, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix For KNN')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

class_accuracy_knn = conf_matrix.diagonal() / conf_matrix.sum(axis=1)


plt.figure(figsize=(18, 6))
sns.barplot(x=knn_model.classes_, y=class_accuracy_knn, color='lightcoral')
plt.title('K-Nearest Neighbors - Prediction Accuracy for Each Class')
plt.xlabel('Activity')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.show()

"""###**Model 3: Naive Bayes Model**###"""

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

nb_model = GaussianNB()
nb_model.fit(X_train, Y_train)
Y_pred_nb = nb_model.predict(X_test)

accuracy_nb = accuracy_score(Y_test, Y_pred_nb)
print(f'Naive Bayes Accuracy: {accuracy_nb:.2f}')

print('Classification Report for Naive Bayes:')
print(classification_report(Y_test, Y_pred_nb))

"""Visualization:"""

from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(Y_test, Y_pred_nb)

plt.figure(figsize=(18, 8))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix for Naive Bayes')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

class_accuracy_knn = conf_matrix.diagonal() / conf_matrix.sum(axis=1)

plt.figure(figsize=(18, 6))
sns.barplot(x=knn_model.classes_, y=class_accuracy_knn, color='lightgreen')
plt.title('Naive Bayes - Prediction Accuracy for Each Class')
plt.xlabel('Activity')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.show()

"""##**Model 4: Logistic Regression**###"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


logistic_model = LogisticRegression(max_iter=200, solver='lbfgs', random_state=42)
logistic_model.fit(X_train, Y_train)
Y_pred_logistic = logistic_model.predict(X_test)

accuracy_logistic = accuracy_score(Y_test, Y_pred_logistic)
print(f'Logistic Regression Accuracy: {accuracy_logistic:.2f}')
print("Classification Report:\n")
print(classification_report(Y_test, Y_pred_logistic))

"""Visualaization"""

from sklearn.metrics import confusion_matrix

conf_matrix_logistic = confusion_matrix(Y_test, Y_pred_logistic)

plt.figure(figsize=(20, 8))
sns.heatmap(conf_matrix_logistic, annot=True, fmt='d', cmap='Blues', xticklabels=logistic_model.classes_, yticklabels=logistic_model.classes_)
plt.title('Confusion Matrix For Logistic Regression')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

class_accuracy_logistic = conf_matrix_logistic.diagonal() / conf_matrix_logistic.sum(axis=1)

plt.figure(figsize=(18, 6))
sns.barplot(x=logistic_model.classes_, y=class_accuracy_logistic, color='#B57EDC')
plt.title('Prediction Accuracy for Logistic Regression')
plt.xlabel('Activity')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
plt.show()